export const Strings = {
    home : "Home",
    name:"Name",
    height:"Height",
    hairColor:"Hair Color",
    films : "Films",
    skinColor:"Skin Color",
    age:"Age",
    mass:"Mass",
    starShips: "StarShips",
    gender:"Gender",
    eyeColor:"Eye Color",
    birthYear:"Birth Year",
    people:"People",
    vehicles:"Vehicles",
    species:"Species",
    planets:"Planets",
    starWar:"Star Wars",
    title:"Title",
    created: "Created",
    director: "Director",
    edited: "Edited",
    openingCrawl: "Opening crawl",
    producer: "Producer",
    releaseDate: "Release Date",
    episode:"Episode",
    characters:"Character",
    view:"View",
}

