export const Strings = {
  home: "Home",
  name: "Name",
  height: "Height",
  hairColor: "Hair Color",
  costInCredits: "Cost In Credits",
  viewFilms: "View Films",
  population: "Population",
  image: "Image",
  films: "Films",
  skinColor: "Skin Color",
  previous: "Previous",
  prev: "Prev",
  back: "Back",
  viewPlanets: "View Planets",
  next: "Next",
  age: "Age",
  dateOfBirth: "Date Of Birth",
  viewVehicle: "View Vehicle",
  viewPeople: "View People",
  viewSpecies: "View Species",
  length: "Length",
  crew: "Crew",
  language: "Language",
  hyperDriveRating: "Hyper Drive Rating",
  diameter: "Diameter",
  gravity: "Gravity",
  model: "Model",
  cargoCapacity: "Cargo Capacity",
  orbitalPeriod: "orbital Period",
  climate: "Climate",
  consumables: "Consumables",
  mglt: "MGLT(MegaLight Per Hour)",
  passengers: "Passengers",
  averageHeight: "Average Height",
  maxAtmosphereSpeed: "Max Atmosphere Speed",
  manufacturer: "Manufacturer",
  averageLifespan: "Average Lifespan",
  designation: "Designation",
  classification: "Classification",
  mass: "Mass",
  starShips: "StarShips",
  gender: "Gender",
  eyeColor: "Eye Color",
  birthYear: "Birth Year",
  starshipClass: "Starship Class",
  viewStarship: "View Starship",
  people: "People",
  vehicles: "Vehicles",
  vehicleClass: "Vehicle Class",
  species: "Species",
  planets: "Planets",
  starWar: "Star Wars",
  title: "Title",
  created: "Created",
  director: "Director",
  residents: "Residents",
  edited: "Edited",
  openingCrawl: "Opening crawl",
  surfaceWater: "Surface Water",
  producer: "Producer",
  releaseDate: "Release Date",
  episode: "Episode",
  terrain: "Terrain",
  characters: "Character",
  view: "View",
  rotationPeriod: "Rotation Period",
};
